using System.Diagnostics.CodeAnalysis;

namespace RelayPulse.Core;

public record Message<T>
{
    /// <summary>
    /// Id to use for the message. If none provided it will be autogenerated
    /// </summary>
    public Guid? Id { get; set; }
    public string? AppId { get; set; }
    public string? Cid { get; set; }
    public string? UserId { get; set; }
    public string? Type { get; set; }
    public string? Tenant { get; set; }
    
    [DisallowNull]
    public T Content { get; set; } = default!;
    public Dictionary<string, string> Headers { get; set; } = new(StringComparer.OrdinalIgnoreCase);
}