namespace RelayPulse.Core;

public record Message<T>
{
    /// <summary>
    /// Id to use for the message. If none provided it will be autogenerated
    /// </summary>
    public Guid? Id { get; init; }
    public string? AppId { get; init; }
    public string? Cid { get; init; }
    public string? UserId { get; init; }
    
    /// <summary>
    /// Optional. default is full name of the type of T
    /// </summary>
    public string Type { get; init; } = typeof(T).FullName ?? typeof(T).Name;
    
    public required T Content { get; init; }
    public Dictionary<string, string> Headers { get; init; } = new(StringComparer.OrdinalIgnoreCase);
}